version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_USER=THE
      - POSTGRES_DB=THE
    ports:
      - "5432:5432"
